name: Release

on:
  push:
    tags:
      - '*.*.*'

permissions:
    contents: write
    packages: write

jobs:
  release:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup
      uses: actions/setup-go@v5
      with:
        go-version: '1.26'
    - name: Build
      run: |
        go mod tidy
        go build -ldflags "-s -w" -v -o bbq
    - name: Optimize
      uses: crazy-max/ghaction-upx@v3
      with:
        version: latest
        files: ./ed
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        prerelease: true
        files: ed
        make_latest: true
